def get_search_terms():
    search_terms = [
        "Housing",
        "Mortgages",
        "Benefits",
        "Savings",
        "Universal Credit",
        "Sickness",
        "Coronavirus",
        "Banking",
        "Insurance",
        "Budgeting",
        "Credit",
        "Running a car",
        "Purchases",
        "Being a parent",
        "Long term care",
        "Death",
        "Bereavement",
        "Student",
        "Talk money",
        "Illness",
        "Disability",
        "Family",
        "Care",
        "Renting",
        "Homes",
        "Debt",
        "Scams",
        "Money Troubles",
        "Complaints",
        "Auto enrollment",
        "State Pension",
        "Retirement",
        "Pension Problems",
        "Tax",
        "Tax and pensions",
        "Pension Basics",
        "Investing",
        "Types of savings",
        "Employment",
        "Losing your job",
        "Self-employment",
    ]
    return search_terms
